require('dotenv').config();
const connectDB = require('./db');
const Restaurant = require('../models/Restaurant');

const restaurants = [
  {
    name: 'Chandni Chowk Restaurant',
    slug: 'chandni-chowk-restaurant',
    tagline: '100+ dishes of pure Mughlai indulgence',
    address: '7-E, Gulberg III, MM Alam Rd, Lahore',
    area: 'Gulberg',
    phone: '+92 333 4232014',
    cuisine: ['Pakistani', 'Mughlai', 'Chinese'],
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    rating: 4.3, review_count: 128, is_featured: true,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2200, price_max: 2200,
        price_label: 'PKR 2,200 + tax',
        timings: '1:00 PM – 4:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Spring Rolls', category: 'Starters' },
          { name: 'Hot & Cold Appetizers', category: 'Starters' },
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Chicken Karahi', category: 'Main Course' },
          { name: 'Daal Mash', category: 'Main Course' },
          { name: 'Mughlai Curry', category: 'Main Course' },
          { name: 'Fruit Raita', category: 'Sides' },
          { name: 'Gol Gappay', category: 'Live Station' },
          { name: 'Live BBQ Grill', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Jalebi', category: 'Desserts' },
          { name: 'Kheer', category: 'Desserts' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Mint Margarita', category: 'Beverages' },
          { name: 'Unlimited Soft Drinks', category: 'Beverages' },
        ],
      },
      {
        type: 'Lunch',
        price_min: 2200, price_max: 2200,
        price_label: 'PKR 2,200 + tax',
        timings: '12:00 PM – 3:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Soup Station', category: 'Starters' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Mutton Karahi', category: 'Main Course' },
          { name: 'Daal Makhani', category: 'Main Course' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Halwa', category: 'Desserts' },
          { name: 'Kheer', category: 'Desserts' },
          { name: 'Soft Drinks', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 2500, price_max: 2500,
        price_label: 'PKR 2,500 + tax',
        timings: '7:00 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Shami Kabab', category: 'Starters' },
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Mutton Karahi', category: 'Main Course' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Chinese Curries', category: 'Main Course' },
          { name: 'Gol Gappay', category: 'Live Station' },
          { name: 'Live BBQ Grill', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Kulfi', category: 'Desserts' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Chai', category: 'Beverages' },
          { name: 'Soft Drinks', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'Ziafat Restaurant',
    slug: 'ziafat-restaurant',
    tagline: 'Unlimited mutton in the heart of MM Alam',
    address: '26-H College Rd (MM Alam Extension), Lahore',
    area: 'Gulberg',
    phone: '+92 345 6789104',
    cuisine: ['Pakistani', 'Mughlai'],
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    rating: 4.5, review_count: 214, is_featured: true,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2640, price_max: 2640,
        price_label: 'PKR 2,640 + tax',
        timings: '1:00–3:00 PM | 3:00–5:00 PM | 5:00–7:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Chicken Fajita Pizza', category: 'Starters' },
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Soup', category: 'Starters' },
          { name: 'Mutton Qorma', category: 'Main Course' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Desi Handis', category: 'Main Course' },
          { name: 'Chinese Items', category: 'Main Course' },
          { name: 'Sada Roti', category: 'Breads' },
          { name: 'Chicken Seekh Kabab', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Live Chaat', category: 'Live Station' },
          { name: 'Kheer', category: 'Desserts' },
          { name: 'Custard', category: 'Desserts' },
          { name: 'Traditional Sweets', category: 'Desserts' },
          { name: 'Soft Drink (per head)', category: 'Beverages' },
          { name: 'Hot Tea', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 2800, price_max: 2800,
        price_label: 'PKR 2,800 + tax',
        timings: '8:00 PM – 10:00 PM', days_available: 'Mon–Thu',
        menu_items: [
          { name: 'Chicken Corn Soup', category: 'Starters' },
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Mutton Palak', category: 'Main Course' },
          { name: 'Chicken Karahi', category: 'Main Course' },
          { name: 'Biryani', category: 'Main Course' },
          { name: '40+ Desi Dishes', category: 'Main Course' },
          { name: 'Chicken Seekh Kabab', category: 'Live Station' },
          { name: 'Live BBQ Skewers', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Kheer', category: 'Desserts' },
          { name: 'Mint Margarita (Welcome Drink)', category: 'Beverages' },
          { name: 'Assorted Cold Drinks', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'Villa The Grand Buffet',
    slug: 'villa-the-grand-buffet-gulberg',
    tagline: "International live stations, Gulberg's grandest spread",
    address: '67 MM Alam Rd, Block B1, Gulberg III, Lahore',
    area: 'Gulberg',
    phone: '+92 304 1111851',
    cuisine: ['Continental', 'Pakistani', 'Chinese', 'Italian', 'Arabic'],
    image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    rating: 4.4, review_count: 319, is_featured: true,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2450, price_max: 2450,
        price_label: 'PKR 2,450 + tax',
        timings: '12:45 PM – 3:15 PM | 3:15 PM – 5:45 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Chicken Pineapple Salad', category: 'Starters' },
          { name: 'Cold Meze', category: 'Starters' },
          { name: 'Fresh Salad Bar', category: 'Starters' },
          { name: 'Soups', category: 'Starters' },
          { name: 'Tempura Fried Vegetables w/ Sweet Chili Sauce', category: 'Starters' },
          { name: 'Chicken Sindhi Biryani', category: 'Desi Main' },
          { name: 'Chicken Black Pepper Karahi', category: 'Desi Main' },
          { name: 'Arabic Cuisine', category: 'Main Course' },
          { name: 'Italian Pasta', category: 'Main Course' },
          { name: 'Egg Fried Rice', category: 'Main (Asian)' },
          { name: 'Rotisserie Chicken', category: 'Live Station' },
          { name: 'Live Sushi / Teppanyaki', category: 'Live Station' },
          { name: 'Live Karahi', category: 'Live Station' },
          { name: 'Live Chaat', category: 'Live Station' },
          { name: 'Molten Chocolate Cake', category: 'Desserts' },
          { name: 'Vanilla Ice Cream (Bottomless)', category: 'Desserts' },
          { name: 'Waffle Station', category: 'Desserts' },
          { name: 'Chocolate Fountain', category: 'Desserts' },
          { name: 'PepsiCo Sodas', category: 'Beverages' },
          { name: 'Unlimited Hot Nescafe', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 3200, price_max: 3200,
        price_label: 'PKR 3,200 + tax',
        timings: '7:00 PM – 9:30 PM | 9:30 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Soups', category: 'Starters' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Multi-Cuisine Global Spread', category: 'Main Course' },
          { name: 'Pan-Asian Dishes', category: 'Main Course' },
          { name: 'Continental Mains', category: 'Main Course' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Live Karahi', category: 'Live Station' },
          { name: 'Live Pasta', category: 'Live Station' },
          { name: 'Massive Dessert Table', category: 'Desserts' },
          { name: 'Chocolate Fountain', category: 'Desserts' },
          { name: 'PepsiCo Sodas', category: 'Beverages' },
          { name: 'Hot Beverages', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'Villa The Grand Buffet – Lake City',
    slug: 'villa-the-grand-buffet-lake-city',
    tagline: 'The grand experience, now at Lake City Mall',
    address: 'Plot C43-25, Canal Commercial, Block M3A, Lake City, Lahore',
    area: 'Lake City',
    phone: '+92 304 1110852',
    cuisine: ['Continental', 'Pakistani', 'Chinese', 'Italian'],
    image_url: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&q=80',
    rating: 4.2, review_count: 87, is_featured: false,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2450, price_max: 2450,
        price_label: 'PKR 2,450 + tax',
        timings: '12:45 PM – 5:45 PM (multiple slots)', days_available: 'Daily',
        menu_items: [
          { name: 'Chicken Pineapple Salad', category: 'Starters' },
          { name: 'Fresh Salad Bar', category: 'Starters' },
          { name: 'Chicken Biryani', category: 'Desi Main' },
          { name: 'Multi-Cuisine Mains', category: 'Main Course' },
          { name: 'Chicken Seekh Kabab', category: 'Live Station' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Chocolate Brownie', category: 'Desserts' },
          { name: 'Ice Cream', category: 'Desserts' },
          { name: 'PepsiCo Sodas', category: 'Beverages' },
          { name: 'Hot Nescafe', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 3200, price_max: 3200,
        price_label: 'PKR 3,200 + tax',
        timings: '7:00 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Multi-Cuisine Spread', category: 'Main Course' },
          { name: 'Pakistani Mains', category: 'Main Course' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Dessert Table', category: 'Desserts' },
          { name: 'Soft Drinks', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'The Carnival',
    slug: 'the-carnival',
    tagline: 'Desi, Thai, Chinese & Continental under one roof',
    address: '118-P, MM Alam Rd, Gulberg II, Lahore',
    area: 'Gulberg',
    phone: '+92 315 5179666',
    cuisine: ['Pakistani', 'Thai', 'Chinese', 'Continental'],
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    rating: 4.1, review_count: 156, is_featured: false,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 1755, price_max: 2300,
        price_label: 'PKR 1,755 – 2,300',
        timings: 'Afternoon slots daily', days_available: 'Daily',
        menu_items: [
          { name: 'Caesar Salad', category: 'Starters' },
          { name: 'Thai Chicken Salad', category: 'Starters' },
          { name: 'Stuffed Chicken', category: 'Starters' },
          { name: 'Unlimited Drinks (Mint Margarita)', category: 'Beverages' },
          { name: 'Bong Paye', category: 'Main Course' },
          { name: 'Nihari', category: 'Main Course' },
          { name: 'Chicken Karahi', category: 'Main Course' },
          { name: 'Continental / Asian Specials', category: 'Main Course' },
          { name: 'Gol Gappay', category: 'Live Station' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Chocolate Fountain', category: 'Desserts' },
          { name: 'Tres Leches', category: 'Desserts' },
          { name: 'Gurr Walay Rice', category: 'Desserts' },
          { name: 'Shot Glass Desserts', category: 'Desserts' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 2200, price_max: 2600,
        price_label: 'PKR 2,200 – 2,600',
        timings: '7:00 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Beef Yakhni Pulao', category: 'Desi Main' },
          { name: 'Chicken Karahi', category: 'Desi Main' },
          { name: 'Mutton Karahi', category: 'Desi Main' },
          { name: 'Biryani', category: 'Main Course' },
          { name: 'Seekh Kabab', category: 'BBQ' },
          { name: 'Chicken Boti', category: 'BBQ' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Chocolate Fountain', category: 'Desserts' },
          { name: 'Soft Drinks', category: 'Beverages' },
        ],
      },
      {
        type: 'Brunch',
        price_min: 1800, price_max: 1800,
        price_label: 'PKR 1,800',
        timings: '11:00 AM – 2:00 PM', days_available: 'Weekends',
        menu_items: [
          { name: 'Breakfast Spread', category: 'Starters' },
          { name: 'Eggs Station', category: 'Live Station' },
          { name: 'Pakistani Mains', category: 'Main Course' },
          { name: 'Soft Drinks', category: 'Beverages' },
          { name: 'Desserts', category: 'Desserts' },
        ],
      },
    ],
  },

  {
    name: "Salt 'n Pepper Village",
    slug: 'salt-n-pepper-village',
    tagline: 'A Lahore institution, perfected over decades',
    address: '103-B, Block Gulberg II, MM Alam Rd, Lahore',
    area: 'Gulberg',
    phone: '',
    cuisine: ['Pakistani', 'Continental', 'Chinese'],
    image_url: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=800&q=80',
    rating: 4.0, review_count: 203, is_featured: false,
    buffets: [
      {
        type: 'Dinner',
        price_min: 3395, price_max: 3395,
        price_label: 'PKR 3,395',
        timings: '7:00 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Mixed Salads & Cold Cuts', category: 'Starters' },
          { name: 'Cheese Platter', category: 'Starters' },
          { name: 'Sushi Rolls', category: 'Starters' },
          { name: 'Shrimp Cocktail', category: 'Starters' },
          { name: 'Cold Soups (Gazpacho)', category: 'Starters' },
          { name: 'Beef Kabuli Pulao', category: 'Main Course' },
          { name: 'Mutton / Chicken Karahi', category: 'Main Course' },
          { name: 'Chinese Options', category: 'Main Course' },
          { name: 'Vegetable Lasagna', category: 'Main Course' },
          { name: 'BBQ Chicken Malai Boti', category: 'Live Station (BBQ)' },
          { name: 'Live Karahi Handis', category: 'Live Station' },
          { name: 'Chocolate Fountain', category: 'Desserts' },
          { name: 'Assorted Pastries', category: 'Desserts' },
          { name: 'Ice Cream', category: 'Desserts' },
          { name: 'Qulfi', category: 'Desserts' },
          { name: 'Gajjar ka Halwa', category: 'Desserts' },
          { name: 'Cotton Candy', category: 'Desserts' },
          { name: 'Hot Beverages', category: 'Beverages' },
          { name: 'Chilled Lassi', category: 'Beverages' },
          { name: 'Fresh Juices', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'Buqayvia Cafe',
    slug: 'buqayvia-cafe',
    tagline: "Fresh hi-tea with 40+ items, Johar Town's new gem",
    address: 'Johar Town, Lahore',
    area: 'Johar Town',
    phone: '+92 300 1780808',
    cuisine: ['Pakistani', 'Continental'],
    image_url: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
    rating: 4.6, review_count: 42, is_featured: true,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2499, price_max: 2499,
        price_label: 'PKR 2,499 (incl. tax, 20% off)',
        timings: '3:30 PM – 5:00 PM | 5:00 PM – 6:30 PM', days_available: 'Daily',
        menu_items: [
          { name: 'German Potato Salad', category: 'Starters' },
          { name: 'Samosas', category: 'Starters' },
          { name: 'Chicken Steak (Black Pepper)', category: 'Main Course' },
          { name: 'Chicken Chowmein', category: 'Main Course' },
          { name: 'Cheesy Penne Pasta', category: 'Main Course' },
          { name: 'Cupcakes', category: 'Desserts' },
          { name: 'Assorted Desserts', category: 'Desserts' },
          { name: 'Mint Margarita (Welcome Drink)', category: 'Beverages' },
          { name: 'Hot Beverages', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'Zaajh',
    slug: 'zaajh',
    tagline: 'French-Italian fine dining, weekend hi-tea perfection',
    address: 'CP-53, Raya Fairways Commercial, Phase 6, DHA, Lahore',
    area: 'DHA',
    phone: '+92 311 1166640',
    cuisine: ['French', 'Italian', 'Continental'],
    image_url: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80',
    rating: 4.7, review_count: 68, is_featured: true,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2295, price_max: 2295,
        price_label: 'PKR 2,295 + tax',
        timings: '2:00 PM – 6:00 PM', days_available: 'Weekends only',
        menu_items: [
          { name: 'Crab Dip', category: 'Starters' },
          { name: 'Avocado Prawns', category: 'Starters' },
          { name: 'Thai Curry Soup', category: 'Starters' },
          { name: 'Mixed Salad', category: 'Starters' },
          { name: 'Lobster Ravioli', category: 'Main Course' },
          { name: 'Gourmet Pasta', category: 'Main Course' },
          { name: 'Chicken Karahi', category: 'Main Course' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Tiramisu', category: 'Desserts' },
          { name: 'Lotus Tiramisu', category: 'Desserts' },
          { name: 'Pistachio / Kunafa Tiramisu', category: 'Desserts' },
          { name: 'Chocolate Paradiso', category: 'Desserts' },
          { name: 'Baklava', category: 'Desserts' },
          { name: 'Artisanal Coffees', category: 'Beverages' },
          { name: 'Specialty Beverages', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'Lal Qila Restaurant',
    slug: 'lal-qila-restaurant',
    tagline: '70+ dishes, daily hi-tea with Mughal grandeur',
    address: 'Plot 11-A Baber Block, New Garden Town, Lahore',
    area: 'Garden Town',
    phone: '+92 304 1115745',
    cuisine: ['Pakistani', 'Mughlai', 'Chinese', 'Continental'],
    image_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    rating: 4.2, review_count: 174, is_featured: false,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2190, price_max: 2190,
        price_label: 'PKR 2,190 (excl. tax)',
        timings: '4:30 PM – 6:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Mint Margarita', category: 'Welcome Drink' },
          { name: 'Fattoush Salad', category: 'Starters' },
          { name: 'International Salads', category: 'Starters' },
          { name: 'Chicken Mandvi Kabab', category: 'Starters' },
          { name: 'Tamarind Wings', category: 'Starters' },
          { name: 'Chicken Alfredo Pasta', category: 'Main Course' },
          { name: 'Garden Spice Special Chicken Biryani', category: 'Main Course' },
          { name: 'Pakistani Specialties', category: 'Main Course' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Kat-a-Kat', category: 'Live Station' },
          { name: 'Gol Gappay', category: 'Live Station' },
          { name: 'Live Chaat', category: 'Live Station' },
          { name: 'Kheer', category: 'Desserts' },
          { name: 'Cheesecake', category: 'Desserts' },
          { name: 'Pastries', category: 'Desserts' },
          { name: 'Unlimited Soft Drinks', category: 'Beverages' },
          { name: 'Specialty Mint Drink', category: 'Beverages' },
        ],
      },
      {
        type: 'Lunch',
        price_min: 2000, price_max: 2000,
        price_label: 'PKR 2,000',
        timings: '12:30 PM – 3:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Hot & Sour Soup', category: 'Starters' },
          { name: 'Fattoush Salad', category: 'Starters' },
          { name: 'Mixed Bean Salad', category: 'Starters' },
          { name: 'Chicken Fajita Tikka', category: 'Starters' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Masala Biryani', category: 'Main Course' },
          { name: 'Chicken Balti Gosht', category: 'Main Course' },
          { name: 'Mughlai Specialties', category: 'Main Course' },
          { name: 'Basbusa', category: 'Desserts' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Vanilla Kulfi', category: 'Desserts' },
          { name: 'Soft Drinks', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 2500, price_max: 2500,
        price_label: 'PKR 2,500',
        timings: '7:30 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Hot & Sour Soup', category: 'Starters' },
          { name: 'Samosa Chat', category: 'Starters' },
          { name: 'Chicken Mandvi Kabab', category: 'Starters' },
          { name: 'International Salads', category: 'Starters' },
          { name: 'Beef Nihari', category: 'Main Course' },
          { name: 'Chicken Qorma', category: 'Main Course' },
          { name: 'Mutton Kunna', category: 'Main Course' },
          { name: 'Egg Fried Rice', category: 'Main Course' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Kat-a-Kat', category: 'Live Station' },
          { name: 'Gol Gappay', category: 'Live Station' },
          { name: 'Chocolate Mousse', category: 'Desserts' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Unlimited Soft Drinks', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'LaMessa \u2013 Indigo Hotel',
    slug: 'lamessa-indigo-hotel',
    tagline: 'Luxury hotel dining, refined buffets in Gulberg',
    address: 'Ground Floor, Indigo Heights, 3-C3 Noor Jehan Rd, Gulberg III, Lahore',
    area: 'Gulberg',
    phone: '+92 316 4778886',
    cuisine: ['Continental', 'Pakistani', 'Chinese', 'Italian'],
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
    rating: 4.5, review_count: 91, is_featured: false,
    buffets: [
      {
        type: 'Hi-Tea',
        price_min: 2150, price_max: 2150,
        price_label: 'PKR 2,150 + tax',
        timings: '1:00 PM – 3:00 PM | 4:00 PM – 6:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Soups', category: 'Starters' },
          { name: 'Variety of Salads', category: 'Starters' },
          { name: 'Kung Pao Chicken', category: 'Main Course' },
          { name: 'Mutton Kofta', category: 'Main Course' },
          { name: 'Lasagna (Beef or Chicken)', category: 'Main Course' },
          { name: 'Chicken Alfredo', category: 'Main Course' },
          { name: 'Live Cooking Station', category: 'Live Station' },
          { name: 'Chocolate Mousse', category: 'Desserts' },
          { name: 'Chocolate Brownies', category: 'Desserts' },
          { name: 'Pastries & Tarts', category: 'Desserts' },
          { name: 'Hot Tea / Coffee', category: 'Beverages' },
          { name: 'PepsiCo Cold Drinks', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 2550, price_max: 2550,
        price_label: 'PKR 2,550 + tax',
        timings: '7:00 PM – 11:00 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Soups', category: 'Starters' },
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Kung Pao Chicken', category: 'Main Course' },
          { name: 'Mutton Kofta', category: 'Main Course' },
          { name: 'Multi-Cuisine Mains (Pakistani, Chinese, Continental)', category: 'Main Course' },
          { name: 'Chicken Tikka', category: 'BBQ' },
          { name: 'Seekh Kabab', category: 'BBQ' },
          { name: 'Live BBQ', category: 'Live Station' },
          { name: 'Live Tawa', category: 'Live Station' },
          { name: 'Chocolate Mousse', category: 'Desserts' },
          { name: 'Cakes', category: 'Desserts' },
          { name: 'Hot Tea / Coffee', category: 'Beverages' },
          { name: 'PepsiCo Cold Drinks', category: 'Beverages' },
        ],
      },
    ],
  },

  {
    name: 'The Garden Spice',
    slug: 'the-garden-spice',
    tagline: 'Asian flavours, canal-side ambiance',
    address: 'Canal Road (adj. Green Forts 2), Lahore',
    area: 'Canal Road',
    phone: '+92 332 3619999',
    cuisine: ['Chinese', 'Thai', 'Pakistani', 'Asian'],
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
    rating: 4.0, review_count: 112, is_featured: false,
    buffets: [
      {
        type: 'Lunch',
        price_min: 2400, price_max: 3200,
        price_label: 'PKR 2,400 – 3,200',
        timings: '12:00 PM – 3:30 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Mint Margarita (Welcome Drink)', category: 'Beverages' },
          { name: 'Honey Wings', category: 'Starters' },
          { name: 'Samosa', category: 'Starters' },
          { name: 'Chana Chaat', category: 'Starters' },
          { name: 'Macaroni Salad', category: 'Salads' },
          { name: 'Garden Spice Special Chicken Biryani', category: 'Main Course' },
          { name: 'Chicken Karahi', category: 'Main Course' },
          { name: 'Chicken Chow Mein', category: 'Main Course' },
          { name: 'Kheer', category: 'Desserts' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Cold Drinks', category: 'Beverages' },
        ],
      },
      {
        type: 'Dinner',
        price_min: 3200, price_max: 4500,
        price_label: 'PKR 3,200 – 4,500',
        timings: '7:00 PM – 11:30 PM', days_available: 'Daily',
        menu_items: [
          { name: 'Soup Station', category: 'Starters' },
          { name: 'Salad Bar', category: 'Starters' },
          { name: 'Chicken Karahi', category: 'Main Course' },
          { name: 'Mutton Qorma', category: 'Main Course' },
          { name: 'Chicken Biryani', category: 'Main Course' },
          { name: 'Egg Fried Rice', category: 'Main Course' },
          { name: 'Chinese Mains', category: 'Main Course' },
          { name: 'Jalebi', category: 'Desserts' },
          { name: 'Gulab Jamun', category: 'Desserts' },
          { name: 'Cold Drinks', category: 'Beverages' },
          { name: 'Hot Tea', category: 'Beverages' },
        ],
      },
    ],
  },
];

const seed = async () => {
  await connectDB();
  await Restaurant.deleteMany({});
  await Restaurant.insertMany(restaurants);
  console.log('Seeded ' + restaurants.length + ' restaurants with full menus');
  process.exit(0);
};

seed();
